spring:
  datasource:
    url: jdbc:h2:mem:olp_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
 
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
 
  flyway:
    enabled: true
    locations: classpath:db/migration-h2
    baseline-on-migrate: true
 
  h2:
    console:
      enabled: true
      path: /h2-console
 
logging:
  level:
    root: INFO
    com.olp: DEBUG
 